- hosts: glusterfs_clients
  tasks:
    - name: Add accept keywords for kuberenetes packages for aarch64 (raspi5)
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../config/static/root/etc/portage/package.accept_keywords/glusterfs"
        dest: "/etc/portage/package.accept_keywords/glusterfs"
      when:
        - ansible_architecture == "aarch64"
    - name: Add use flags
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../config/static/root/etc/portage/package.use/glusterfs"
        dest: "/etc/portage/package.use/glusterfs"
    - name: Install gluster fs
      community.general.portage:
        package: sys-cluster/glusterfs
        getbinpkg: true
- hosts: glusterfs_nodes
  tasks:
    - name: Install gluster fs
      community.general.portage:
        package: sys-cluster/glusterfs
        getbinpkg: true
    - name: enable glusterd service
      ansible.builtin.service:
        name: glusterd
        enabled: yes
        runlevel: default
    - name: Start glusterd
      ansible.builtin.service:
        name: glusterd
        state: started
