- hosts: kubernetes_control_plane

  tasks: 
    - name: Stop server services
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
      loop:
        - kube-controller-manager
        - kube-scheduler
    - name: Stop api-server
      ansible.builtin.service:
        name: kube-apiserver
        state: stopped
    - name: Disable kubernetes server services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: false
      loop:
        - kube-controller-manager
        - kube-scheduler
        - kube-apiserver
    - name: Uninstalling kubernetes server packages
      community.general.portage:
        package: "{{ item }}"
        state: absent
        depclean: true
      loop:
        - sys-cluster/kubectl
        - sys-cluster/kube-apiserver
        - sys-cluster/kube-controller-manager
        - sys-cluster/kube-scheduler
    - name: Remove uneeded packages
      community.general.portage:
        depclean: true
    - name: Remove dirs/files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/init.d/kube-apiserver
        - /etc/init.d/kube-controller-manager
        - /etc/init.d/kube-scheduler
        - /root/admin.kubeconfig
        - /root/kube-controller-manager.kubeconfig
        - /root/kube-scheduler.kubeconfig
# Note: commented section because of dependency with etcd
#       the design right now is etcd and control plane lives in the same host
#       - /etc/etcd/ca.key
#       - /etc/etcd/ca.crt # Should be symlink but its okay for now.
#       - /var/lib/kubernetes/pki/ca.key
#       - /var/lib/kubernetes/pki/ca.crt
        - /var/lib/kubernetes/pki/kube-apiserver.key
        - /var/lib/kubernetes/pki/kube-apiserver.crt
        - /var/lib/kubernetes/pki/service-account.key
        - /var/lib/kubernetes/pki/service-account.crt
        - /var/lib/kubernetes/pki/apiserver-kubelet-client.key
        - /var/lib/kubernetes/pki/apiserver-kubelet-client.crt
        - /var/lib/kubernetes/pki/etcd-server.key
        - /var/lib/kubernetes/pki/etcd-server.crt
        - /var/lib/kubernetes/pki/kube-scheduler.key
        - /var/lib/kubernetes/pki/kube-scheduler.crt
        - /var/lib/kubernetes/pki/kube-controller-manager.key
        - /var/lib/kubernetes/pki/kube-controller-manager.crt
