- hosts: kubernetes_worker
  tasks: 
    - name: Stop services
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
      loop:
        - containerd
        - kubelet
        - kube-proxy
    - name: Disable services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: false
        runlevel: default
      loop:
        - containerd
        - kubelet
        - kube-proxy
    - name: Uninstall kubernetes apps for nodes
      community.general.portage:
        package: "{{ item }}"
        state: absent
      loop:
        - app-containers/containerd
        - app-containers/cni-plugins
        - net-firewall/ipset
        - sys-cluster/kubectl
        - sys-cluster/ipvsadm
        - sys-cluster/kubelet
        - sys-cluster/kube-proxy
    - name: Remove uneeded packages
      community.general.portage:
        depclean: true
    - name: Remove dirs/files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/init.d/kubelet
        - /etc/init.d/kube-proxy
          # - /var/lib/kubernetes/pki/node-{{ iid.name }}.key
          # - /var/lib/kubernetes/pki/node-{{ iid.name }}.crt
          # - /var/lib/kubernetes/pki/ca.crt
        - /var/lib/kubernetes/pki/kube-proxy.key
        - /var/lib/kubernetes/pki/kube-proxy.crt
        - /var/lib/kube-proxy/kube-proxy.kubeconfig
        - /var/lib/kubelet/kubelet.kubeconfig
        - /var/lib/kubelet/kubelet-config.yaml
        - /var/lib/kube-proxy/kube-proxy-config.yaml
    - name: Reenable SWAP in fstab (1/2)
      replace:
        path: /etc/fstab
        regexp: '^# (.+?\sswap\s+sw\s+.*)$'
        replace: '\1'
    - name: Enable SWAP (2/2)
      shell: |
        swapon -a

