- hosts:
  - kubernetes_control_plane
  - kubernetes_nodes

  tasks:
    - name: Delete routes
      ansible.builtin.shell:
        cmd: ip route del "{{ item.to }}" via "{{ item.via }}"
      loop: "{{ pods_routes | selectattr('node', 'equalto', iid.name) | map(attribute='routes') | flatten }}"
