- hosts: kubernetes_nodes

  tasks: 
    - name: display messages
      debug:
        msg:
          - "Current host: {{ iid.name }}"
      tags:
        - msg123
    - name: Add accept keywords for kuberenetes packages for aarch64 (raspi5)
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../config/static/root/etc/portage/package.accept_keywords/kubernetes"
        dest: "/etc/portage/package.accept_keywords/kubernetes"
      when:
        - ansible_architecture == "aarch64"
    - name: install kubernetes apps for nodes
      community.general.portage:
        package: "{{ item }}"
        state: present
        getbinpkg: true
      loop:
        - app-containers/containerd
        - app-containers/cni-plugins
        - sys-cluster/kubelet
        - sys-cluster/kube-proxy
    - name: create dirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - /etc/cni/net.d
        - /opt/cni/bin
        - /etc/containerd
        - /var/lib/kubelet
        - /var/lib/kube-proxy
        - /var/lib/kubernetes
        - /var/run/kubernetes
    - name: Create kubelet dir
      ansible.builtin.file:
        path: /var/lib/kubelet
        state: directory
        mode: '0755'
    - name: Transfer certs
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../config/certs/generated/{{ iid.name }}.crt"
        dest: /var/lib/kubelet/kubelet.crt
        owner: root
        group: root
        mode: '0644'
    - name: Transfer certs
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../config/certs/generated/ca.crt"
        dest: /var/lib/kubelet/ca.crt
        owner: root
        group: root
        mode: '0644'
    - name: Transfer certs 2
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../config/certs/generated/{{ iid.name }}.key"
        dest: /var/lib/kubelet/kubelet.key
        owner: root
        group: root
        mode: '0400'
    - name: Transfer certs 2
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../config/certs/generated/ca.key"
        dest: /var/lib/kubelet/ca.key
        owner: root
        group: root
        mode: '0400'
    - name: Create kube-proxy dir
      ansible.builtin.file:
        path: /var/lib/kube-proxy
        state: directory
        mode: '0755'
    - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
      shell: |
        swapoff -a
    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
    - name: fill and transfer templated configs
      ansible.builtin.template:
        src: "{{ item.file }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - { file: "{{ playbook_dir }}/../../config/templates/10-bridge.conf.j2", dest: /etc/cni/net.d/10-bridge.conf }
        - { file: "{{ playbook_dir }}/../../config/templates/kubelet-config.yaml.j2", dest: /var/lib/kubelet/kubelet-config.yaml }
      tags:
        - test123
    - name: transfer non templated configs
      ansible.builtin.copy:
        src: "{{ item.file }}"
        dest:  "{{ item.dest }}"
        owner: root
        group: root
      loop:
        - { file: "{{ playbook_dir }}/../../config/certs/generated/kube-proxy.kubeconfig",dest: /var/lib/kube-proxy/kubeconfig }
        - { file: "{{ playbook_dir }}/../../config/certs/generated/{{ iid.name }}.kubeconfig", dest: /var/lib/kubelet/kubeconfig }
        - { file: "{{ playbook_dir }}/../../config/static/99-loopback.conf", dest: /etc/cni/net.d/99-loopback.conf }
        - { file: "{{ playbook_dir }}/../../config/static/containerd-config.toml", dest: /etc/containerd/containerd-config.toml }          
        - { file: "{{ playbook_dir }}/../../config/static/kube-proxy-config.yaml", dest: /var/lib/kube-proxy/kube-proxy-config.yaml }
    - name: enable kubernetes server services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: yes
        runlevel: default
      loop:
        - containerd
        - kubelet
        - kube-proxy
    - name: Modify kube-scheduler init file
      ansible.builtin.lineinfile:
        path: /etc/init.d/kubelet
        regexp: '^command_args='
        state: present
        line: command_args="
          --config=/var/lib/kubelet/kubelet-config.yaml
          --kubeconfig=/var/lib/kubelet/kubeconfig
          --register-node=true
          --v=2
          ${command_args}"
    - name: Modify kube-proxy init file
      ansible.builtin.lineinfile:
        path: /etc/init.d/kube-proxy
        regexp: '^command_args='
        state: present
        line: command_args="
          --config=/var/lib/kube-proxy/kube-proxy-config.yaml
          ${command_args}"
    - name: Start services
      ansible.builtin.service:
        name: "{{ item }}"
          #state: started
        state: restarted
      loop:
        - containerd
        - kubelet
        - kube-proxy
      tags:
        - just_restart

