- hosts:
  - kubernetes_control_plane
  - kubernetes_nodes

  tasks:
    - name: display messages
      debug:
        msg:
          - "{{ item.to }} via {{ item.via }}"
      loop: "{{ pods_routes | selectattr('node', 'equalto', iid.name) | map(attribute='routes') | flatten }}"
      tags:
        - msg123
    - name: Add routes # When this task fails, it means that the routes are already there. Technically it is idempotent.
      ansible.builtin.shell:
        cmd: ip route add "{{ item.to }}" via "{{ item.via }}"
      loop: "{{ pods_routes | selectattr('node', 'equalto', iid.name) | map(attribute='routes') | flatten }}"
