- hosts: kubernetes_control_plane

  tasks: 
    - name: Stop server services
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
      loop:
        - kube-apiserver
        - kube-controller-manager
        - kube-scheduler
    - name: Disable kubernetes server services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: false
      loop:
        - kube-apiserver
        - kube-controller-manager
        - kube-scheduler
    - name: Uninstalling kubernetes server packages
      community.general.portage:
        package: "{{ item }}"
        state: absent
        depclean: true
      loop:
        - sys-cluster/kubectl
        - sys-cluster/kube-apiserver
        - sys-cluster/kube-controller-manager
        - sys-cluster/kube-scheduler
    - name: Remove uneeded packages
      community.general.portage:
        depclean: true
    - name: Remove dirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/kubernetes
    - name: Remove files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/init.d/kube-apiserver
        - /etc/init.d/kube-controller-manager
        - /etc/init.d/kube-scheduler
        - /root/admin.kubeconfig
        - /root/kube-controller-manager.kubeconfig
        - /root/kube-scheduler.kubeconfig
