- hosts: un100d02
  tasks: 
    - name: Add accept keywords for kuberenetes packages for aarch64 (raspi5)
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../config/static/root/etc/portage/package.accept_keywords/k8s_workers.conf"
        dest: "/etc/portage/package.accept_keywords/k8s_workers.conf"
      when:
        - ansible_architecture == "aarch64"
    - name: install kubernetes apps for nodes
      community.general.portage:
        package: "{{ item }}"
        state: present
        getbinpkg: true
      loop:
        - app-containers/containerd
        - app-containers/cni-plugins
        - net-firewall/ipset
        - sys-cluster/kubectl
        - sys-cluster/ipvsadm
        - sys-cluster/kubelet
        - sys-cluster/kube-proxy
    - name: create dirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - /var/lib/kubelet
        - /var/lib/kube-proxy
        - /var/lib/kubernetes
        - /var/lib/kubernetes/pki
        - /var/run/kubernetes
    - name: Transfer Certs
      ansible.builtin.copy:
        src: "{{ item.file }}" 
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.perm }}"
      loop:
        # TODO: permissions are not correct here
        - { file: "{{ playbook_dir }}/../../config/certs/generated/node-{{ iid.name }}.key", perm: '0777', dest: /var/lib/kubernetes/pki/ }
        - { file: "{{ playbook_dir }}/../../config/certs/generated/node-{{ iid.name }}.crt", perm: '0777', dest: /var/lib/kubernetes/pki/ }
        - { file: "{{ playbook_dir }}/../../config/certs/generated/ca.crt", perm: '0777', dest: /var/lib/kubernetes/pki/ }
        - { file: "{{ playbook_dir }}/../../config/certs/generated/kube-proxy.key", perm: '0777', dest: /var/lib/kubernetes/pki/ }
        - { file: "{{ playbook_dir }}/../../config/certs/generated/kube-proxy.crt", perm: '0777', dest: /var/lib/kubernetes/pki/ }
        - { file: "{{ playbook_dir }}/../../config/certs/generated/kube-proxy.kubeconfig", perm: '0777', dest: /var/lib/kube-proxy/ }
        - { file: "{{ playbook_dir }}/../../config/certs/generated/node-{{ iid.name }}.kubeconfig", perm: '0777', dest: /var/lib/kubelet/kubelet.kubeconfig }
    - name: fill and transfer templated configs
      ansible.builtin.template:
        src: "{{ item.file }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - { file: "{{ playbook_dir }}/../../config/templates/root/var/lib/kubelet/kubelet-config.yaml.j2", dest: /var/lib/kubelet/kubelet-config.yaml }
        - { file: "{{ playbook_dir }}/../../config/templates/root/var/lib/kube-proxy/kube-proxy-config.yaml.j2", dest: /var/lib/kube-proxy/kube-proxy-config.yaml }
        - { file: "{{ playbook_dir }}/../../config/templates/root/var/lib/kube-proxy/kube-proxy-config.yaml.j2", dest: /var/lib/kube-proxy/kube-proxy-config.yaml }
    - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
      shell: |
        swapoff -a
    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
    - name: enable kubernetes server services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: yes
        runlevel: default
      loop:
        - containerd
        - kubelet
        - kube-proxy
    - name: Modify kube-scheduler init file
      ansible.builtin.lineinfile:
        path: /etc/init.d/kubelet
        regexp: '^command_args='
        state: present
        line: command_args="
          --config=/var/lib/kubelet/kubelet-config.yaml
          --kubeconfig=/var/lib/kubelet/kubelet.kubeconfig
          --register-node=true
          --node-ip={{ iid.name }}
          --v=2
          ${command_args}"
    - name: Modify kube-proxy init file
      ansible.builtin.lineinfile:
        path: /etc/init.d/kube-proxy
        regexp: '^command_args='
        state: present
        line: command_args="
          --config=/var/lib/kube-proxy/kube-proxy-config.yaml
          ${command_args}"
    - name: Start services
      ansible.builtin.service:
        name: "{{ item }}"
          #state: started
        state: restarted
      loop:
        - containerd
        - kubelet
        - kube-proxy
      tags:
        - just_restart

