- hosts: glusterfs_nodes
  tasks:
    - name: include vars
      ansible.builtin.include_vars:
        file: glusterfs_vars.yaml 
        name: glusterfs_vars
    - name: stop volume
      gluster.gluster.gluster_volume:
        state: stopped
        name: "{{ glusterfs_vars.volume_name }}"
      run_once: true
- hosts: glusterfs_nodes
  tasks:
    - name: include vars
      ansible.builtin.include_vars:
        file: glusterfs_vars.yaml 
        name: glusterfs_vars
    - name: remove brick from cluster
      ansible.builtin.file:
        path: "{{ iid.mount_point }}/{{ glusterfs_vars.brick_name }}"
        state: absent
- hosts: glusterfs_nodes
  tasks:
    - name: include vars
      ansible.builtin.include_vars:
        file: glusterfs_vars.yaml 
        name: glusterfs_vars
    - name: remove volume
      gluster.gluster.gluster_volume:
        state: absent
        name: "{{ glusterfs_vars.volume_name }}"
      run_once: true
