- hosts: glusterfs_clients
  tasks:
    - name: create kernel module folder
      ansible.builtin.file:
        path: /etc/modules-load.d
        state: directory
    - name: create kernel module load for fuse
      ansible.builtin.file:
        path: /etc/modules-load.d/fuse.conf
        state: touch
    - name: add needed kernel modules so that it is loaded during boot
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/fuse.conf
        regexp: '^fuse'
        line: fuse
    - name: reboot
      ansible.builtin.reboot:
