- hosts: glusterfs_nodes
  tasks:
    - name: Install parted
      community.general.portage:
        package: sys-block/parted
        getbinpkg: true
    - name: Create 1 partition for whole drive
      community.general.parted:
        device: "{{ iid.drive }}"
        number: 1
        label: gpt
        fs_type: xfs
        state: present
    - name: format partition to be xfs
      community.general.filesystem:
        fstype: xfs
        dev: "{{ iid.drive_partition }}"
          #force: true
        # I wish there was an option like "if fstype doesnt match, format still". 
    - name: Create mount point folder
      ansible.builtin.file:
        path: "/export/{{ iid.partition }}"
        state: directory
    - name: add mountpoint to fstab # this should also include mounting but the module doesn't do that.
      ansible.posix.mount:
        path: "{{ iid.mount_point }}"
        src: "{{ iid.drive_partition }}"
        fstype: xfs
        opts: defaults,noatime
        state: present # putting "mounted" results in failure when it is already mounted, idempotency and all...
    - name: call mount -a instead
      ansible.builtin.shell: mount -a
      args:
        executable: /bin/bash
      

